//------------------------------------------------------------------------------
// <auto-generated>
//    Ten kod źródłowy został wygenerowany na podstawie szablonu.
//
//    Ręczne modyfikacje tego pliku mogą spowodować nieoczekiwane zachowanie aplikacji.
//    Ręczne modyfikacje tego pliku zostaną zastąpione w przypadku ponownego wygenerowania kodu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projekt_bazodanowy
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zawodnik
    {
        public int zawodnik_id { get; set; }
        public string nazwisko { get; set; }
        public int numer { get; set; }
        public System.DateTime data_urodzin { get; set; }
    }
}
