//------------------------------------------------------------------------------
// <auto-generated>
//    Ten kod źródłowy został wygenerowany na podstawie szablonu.
//
//    Ręczne modyfikacje tego pliku mogą spowodować nieoczekiwane zachowanie aplikacji.
//    Ręczne modyfikacje tego pliku zostaną zastąpione w przypadku ponownego wygenerowania kodu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projekt_bazodanowy
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [Serializable]
    [DataContract(IsReference = true)]
    public partial class Zespol
    {
        //public Zespol()
        //{
        //    this.Trener = new HashSet<Trener>();
        //    this.Zawodnik = new HashSet<Zawodnik>();
        //}
    
        [DataMember]
        public int zespol_id { get; set; }
        [DataMember]
        public string nazwa { get; set; }

        //[DataMember]
        //public virtual Prezes Prezes { get; set; }
        //[DataMember]
        //public virtual ICollection<Trener> Trener { get; set; }
        //[DataMember]
        //public virtual Hala Hala { get; set; }
        //[DataMember]
        //public virtual ICollection<Zawodnik> Zawodnik { get; set; }
    }
}
